---
# Copyright 2026 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: 70-helm_csi_rbd-install | all
  hosts: all
  remote_user: root
  become: true

- name: 70-helm_csi_rbd-install | ceph_mon
  hosts: ceph_mon
  remote_user: root
  become: true
  tasks:
    - name: ceph health detail
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          ceph crash archive-all && ceph health detail | grep 'HEALTH_OK'
      args:
        executable: /bin/bash
      when: inventory_hostname == groups['ceph_mon'][0]
      register: result
      changed_when: result is not succeeded
      until: result is succeeded
      retries: 60

- name: 70-helm_csi_rbd-install | kube_master
  hosts: kube_master
  remote_user: root
  become: true
  tasks:
    - name: kubectl get --raw='/readyz?verbose'
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          kubectl get --raw='/readyz?verbose' | grep 'check passed'
      args:
        executable: /bin/bash
      when: inventory_hostname == groups['kube_master'][0]
      register: result
      changed_when: result is not succeeded
      until: result is succeeded
      retries: 60

    - name: kubectl version --output=yaml
      ansible.builtin.command:
        cmd: kubectl version --output=yaml
      register: result
      changed_when: result is not succeeded

    - name: include role
      ansible.builtin.include_role:
        name: helm

    - name: include role
      ansible.builtin.include_role:
        name: ceph_common

    - name: fetch ceph client.admin key
      ansible.builtin.shell:
        cmd: |
          set -euxo pipefail
          ceph auth get-key client.admin
      args:
        executable: /bin/bash
      delegate_to: "{{ groups['ceph_mon'][0] }}"
      register: ceph_client_admin_result
      changed_when: ceph_client_admin_result is not succeeded

    - name: include role
      ansible.builtin.include_role:
        name: helm_csi_snapshotter

    - name: include role
      ansible.builtin.include_role:
        name: helm_csi_rbd
      vars:
        helm_csi_rbd_admin_secret: "{{ ceph_client_admin_result.stdout }}"
